Repository CESARBR/knot-fog-connector-fiware, pull requests merged in 2019-12, with the labels that each got.

#10 Verify if data is encoded before publishing
  src/Connector.js
Labels: priority: medium

#17 Add device authentication (close #5)
  src/Connector.js
Labels: enhancement, priority: medium

#18 Bump to v3.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: priority: high
